services:
  stream-icecast:
    build: ./icecast # build image from directory
    ports: 
      - "8000:8000"
    volumes:
      - icecast-logs:/var/log/icecast/
    env_file:
      - ./auth.env
      - ./.env

  fallback-stream:
    build: ./liquidsoap
    env_file:
      - ./auth.env
      - ./.env
    volumes:
      - fallback-music:/music

  music-filebrowser:
    image: filebrowser/filebrowser:s6
    ports:
      - "8080:80"
    volumes:
      - fallback-music:/srv:rw
      - filebrowser-db:/database:rw
      - filebrowser-config:/config:rw

volumes:
  icecast-logs:
    # name: "icecast-logs"
  fallback-music:
    # name: "fallback-music"
  filebrowser-db:
  filebrowser-config: