apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liquidsoap-music-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: azurefile
  resources:
    requests:
      storage: 15Gi